# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RecycleBIM
email: your-email@example.com
description: Integrated Planning and Recording Circularity of Construction Materials through Digital Modelling
url: https://muniz1994.github.io/
baseurl: 

github_username: Muniz1994

# Build settings

logo: /img/RecycleBIM-logo.png
permalink: /:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

social:
  - title: linkedin
    url:

collections:
  partners:
    sort_by: part-no
  news:
    output: true
    permalink: /:collection/:title:output_ext
  advboard:
    output: true
    permalink: /:collection/:title:output_ext
  portfolio: